language: python
os: linux

dist: xenial

jobs:
  include:
    - os: linux
      python: 2.7
      env:
        - NUMPY_VERSION=1.14
    - os: linux
      python: 2.7
      env:
        - NUMPY_VERSION=1.16
    - os: linux
      python: 3.6
      env:
        - NUMPY_VERSION=1.16
    - os: linux
      python: 3.8
      env:
        - NUMPY_VERSION=1.19

install:
  # Install Miniconda
  - if [[ "$TRAVIS_PYTHON_VERSION" == "2.7" ]]; then
      wget http://repo.continuum.io/miniconda/Miniconda2-latest-Linux-x86_64.sh -O miniconda.sh;
    else
      wget http://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
    fi
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  # useful for debugging purposes
  - conda info -a

  # Setup environment
  - conda create -q -n test-environment  python=${TRAVIS_PYTHON_VERSION:0:3} numpy=${NUMPY_VERSION} nose mkl
  - source activate test-environment

  # Build extensions without silencing compile errors
  - python setup.py install

script:
  - cd ~ ; python -m gulinalg.testing -b

