# To use:
#   $ conda env create -f environment.yml  # `mamba` works too for this command
#   $ conda activate scipy-dev
#
name: gulinalg
channels:
  - conda-forge
dependencies:
  - python==3.11
  - compilers
  #- numpy==1.26.4
  - numpy
  - openblas
  - pkg-config
  - libblas=*=*openblas  # helps avoid pulling in MKL
