name: Linux tests

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  test_meson:
    name: build and run tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.11"]

    steps:
    - uses: actions/checkout@v4.1.1
      with:
        submodules: recursive

    - name: Setup Conda
      uses: conda-incubator/setup-miniconda@v3
      with:
        python-version: ${{ matrix.python-version }}
        channels: conda-forge
        channel-priority: true
        activate-environment: gulinalg
        use-only-tar-bz2: false
        miniforge-variant: Mambaforge
        miniforge-version: latest
        use-mamba: true

    - name: Update Conda Environment
      run: mamba env update -n gulinalg -f environment.yml

    - name: Build and test gulinalg
      shell: bash -l {0}
      run: |
        conda activate gulinalg
        mamba list
        # pip install gulinalg -e . -v   # fails to build, why?
        export PYTHONPATH=`pwd`
        python setup.py build_ext -i
        python -c'import gulinalg as g; g.test()'
